print("Welcome to the band name generator")
city = input("Which city did you grow up in?\n")
print(city)
pet = input("what is the name of the pet\n")
print("Your band name could be: " + city + " " + pet)
